insert into chuong_trinh_phat_thanh (active,name,name_url,link_mp3,file_mp3,noi_dung,title,keyword,description) values ('1','Chương trình PT: 13 - 02 - 2017','chuong-trinh-pt-13-02-2017','','/daituson/view/admin/Themes/kcfinder/upload/images/file_mp3/13_2_17/CT_32%2C_13_-_2_-_2017.mp3','<p>
	<span style=\"color: rgb(60, 59, 59); font-family: helvetica; font-size: 15px; text-align: justify;\">Hưởng ứng phong tr&agrave;o x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, những năm qua thị uỷ, UBND thị x&atilde; Từ Sơn đ&atilde; t&iacute;ch cực chỉ đạo c&aacute;c ng&agrave;nh đo&agrave;n thể v&agrave; c&aacute;c x&atilde;, phường tr&ecirc;n địa b&agrave;n tập trung mọi nguồn lực thực hiện c&aacute;c chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới. &nbsp;T&iacute;nh đến hết năm 2015, to&agrave;n thị x&atilde; c&oacute; 4/5 x&atilde; đ&atilde; ho&agrave;n th&agrave;nh 19/19 ti&ecirc;u ch&iacute; được c&ocirc;ng nhận đạt ti&ecirc;u chuẩn x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, &nbsp;c&ograve;n lại x&atilde; Tam Sơn l&agrave; đơn vị cuối c&ugrave;ng của thị x&atilde; chưa ho&agrave;n th&agrave;nh chỉ ti&ecirc;u. Với mục ti&ecirc;u 100% x&atilde; tr&ecirc;n địa b&agrave;n đạt ti&ecirc;u chuẩn về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới để tạo tiền đề cho Từ Sơn sớm trở th&agrave;nh đ&ocirc; thị loại 3 văn minh hiện đại v&agrave;o năm 2020, Thị x&atilde; đ&atilde; chỉ đạo x&atilde; Tam Sơn phấn đấu trong năm 2016 sẽ ho&agrave;n th&agrave;nh 19/19 chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới.</span></p>
','Chương trình PT: 13 - 02 - 2017','Chương trình PT: 13 - 02 - 2017','Chương trình PT: 13 - 02 - 2017');
insert into chuong_trinh_phat_thanh (active,name,name_url,link_mp3,file_mp3,noi_dung,title,keyword,description) values ('1','Chương trình PT: 14 - 2 - 2017','chuong-trinh-pt-14-2-2017','','/daituson/view/admin/Themes/kcfinder/upload/images/file_mp3/14_02_17/CT_33%2C_14_-_2_-_2017.mp3','<p>
	<span style=\"color: rgb(60, 59, 59); font-family: helvetica; font-size: 15px; text-align: justify;\">Hưởng ứng phong tr&agrave;o x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, những năm qua thị uỷ, UBND thị x&atilde; Từ Sơn đ&atilde; t&iacute;ch cực chỉ đạo c&aacute;c ng&agrave;nh đo&agrave;n thể v&agrave; c&aacute;c x&atilde;, phường tr&ecirc;n địa b&agrave;n tập trung mọi nguồn lực thực hiện c&aacute;c chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới. &nbsp;T&iacute;nh đến hết năm 2015, to&agrave;n thị x&atilde; c&oacute; 4/5 x&atilde; đ&atilde; ho&agrave;n th&agrave;nh 19/19 ti&ecirc;u ch&iacute; được c&ocirc;ng nhận đạt ti&ecirc;u chuẩn x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, &nbsp;c&ograve;n lại x&atilde; Tam Sơn l&agrave; đơn vị cuối c&ugrave;ng của thị x&atilde; chưa ho&agrave;n th&agrave;nh chỉ ti&ecirc;u. Với mục ti&ecirc;u 100% x&atilde; tr&ecirc;n địa b&agrave;n đạt ti&ecirc;u chuẩn về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới để tạo tiền đề cho Từ Sơn sớm trở th&agrave;nh đ&ocirc; thị loại 3 văn minh hiện đại v&agrave;o năm 2020, Thị x&atilde; đ&atilde; chỉ đạo x&atilde; Tam Sơn phấn đấu trong năm 2016 sẽ ho&agrave;n th&agrave;nh 19/19 chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới.</span></p>
','Chương trình PT: 14 - 2 - 2017','Chương trình PT: 14 - 2 - 2017','Chương trình PT: 14 - 2 - 2017');
insert into chuong_trinh_phat_thanh (active,name,name_url,link_mp3,file_mp3,noi_dung,title,keyword,description) values ('1','Chương trình PT: 15 - 2 - 2017','chuong-trinh-pt-15-2-2017','','/daituson/view/admin/Themes/kcfinder/upload/images/file_mp3/15_02_17/CT_34%2C_15_-_2_-_2017.mp3','<p>
	<span style=\"color: rgb(60, 59, 59); font-family: helvetica; font-size: 15px; text-align: justify;\">Hưởng ứng phong tr&agrave;o x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, những năm qua thị uỷ, UBND thị x&atilde; Từ Sơn đ&atilde; t&iacute;ch cực chỉ đạo c&aacute;c ng&agrave;nh đo&agrave;n thể v&agrave; c&aacute;c x&atilde;, phường tr&ecirc;n địa b&agrave;n tập trung mọi nguồn lực thực hiện c&aacute;c chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới. &nbsp;T&iacute;nh đến hết năm 2015, to&agrave;n thị x&atilde; c&oacute; 4/5 x&atilde; đ&atilde; ho&agrave;n th&agrave;nh 19/19 ti&ecirc;u ch&iacute; được c&ocirc;ng nhận đạt ti&ecirc;u chuẩn x&acirc;y dựng n&ocirc;ng th&ocirc;n mới, &nbsp;c&ograve;n lại x&atilde; Tam Sơn l&agrave; đơn vị cuối c&ugrave;ng của thị x&atilde; chưa ho&agrave;n th&agrave;nh chỉ ti&ecirc;u. Với mục ti&ecirc;u 100% x&atilde; tr&ecirc;n địa b&agrave;n đạt ti&ecirc;u chuẩn về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới để tạo tiền đề cho Từ Sơn sớm trở th&agrave;nh đ&ocirc; thị loại 3 văn minh hiện đại v&agrave;o năm 2020, Thị x&atilde; đ&atilde; chỉ đạo x&atilde; Tam Sơn phấn đấu trong năm 2016 sẽ ho&agrave;n th&agrave;nh 19/19 chỉ ti&ecirc;u về x&acirc;y dựng n&ocirc;ng th&ocirc;n mới.</span></p>
','Chương trình PT: 15 - 2 - 2017','Chương trình PT: 15 - 2 - 2017','Chương trình PT: 15 - 2 - 2017');
