update config set banner='/daituson/view/admin/Themes/kcfinder/upload/images/config/logodaituson.jpg',icon='/daituson/view/admin/Themes/kcfinder/upload/images/config/favicon.jpg',name='Đài phát thanh Từ Sơn | Thời sự tổng hợp',dien_thoai='02413.835.112',fax='02416.260.112',email='phatthanhtuson@gmail.com',tru_so='Khu trung tâm TX Từ Sơn - Bắc Ninh.',giay_phep='Website Đài phát thanh TX Từ Sơn được Bộ TT và TT cấp phép hoạt động theo giấy phép số 116/GP-TTĐT từ tháng 9/2009.',trach_nhiem_chinh='Trưởng Đài - Nguyễn Đình Minh.',trach_nhiem_noi_dung='Phó Trưởng Đài - Nguyễn Thị Châu Loan.',gioi_thieu='<p>
	&nbsp;</p>
<p align=\"center\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px;\">
	<strong style=\"margin: 0px; padding: 0px;\">Từ Sơn con người - truyền thống văn hiến c&aacute;ch mạng</strong></p>
<p align=\"center\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px;\">
	<strong style=\"margin: 0px; padding: 0px;\">&nbsp;</strong></p>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Từ Sơn vốn l&agrave; v&ugrave;ng qu&ecirc; gi&agrave;u truyền thống văn hiến v&agrave; c&aacute;ch mạng, qu&ecirc; hương của Vương triều L&yacute; với Đền Đ&ocirc; một di t&iacute;ch lịch sử nổi tiếng. Trải qua bao thế hệ c&ugrave;ng những thăng trầm của lịch sử, nơi đ&acirc;y đ&atilde; sản sinh ra những con người ưu t&uacute; ti&ecirc;u biểu như: Ng&ocirc; Gia Tự - Người chiến sĩ c&aacute;ch mạng lỗi lạc của Đảng ta, Nguyễn Văn Cừ - cố Tổng b&iacute; thư, một tấm gương c&aacute;ch mạng kiệt xuất của Đảng, v&agrave; c&ograve;n nhiều khoa bảng t&agrave;i hoa, đỗ đạt cao l&agrave;m rạng rỡ qu&ecirc; hương đất nước. Người Từ Sơn lu&ocirc;n tự h&agrave;o về điều đ&oacute; v&agrave; kh&ocirc;ng ngừng phấn đấu vươn l&ecirc;n để x&acirc;y dựng qu&ecirc; hương ng&agrave;y c&agrave;ng gi&agrave;u đẹp văn minh.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Theo c&aacute;c nguồn t&agrave;i liệu cổ v&agrave; khảo cổ học từ thời đại H&ugrave;ng Vương, v&ugrave;ng đất Từ Sơn đ&atilde; c&oacute; nhiều bộ tộc người Việt sinh sống dọc theo đ&ocirc;i bờ s&ocirc;ng Ti&ecirc;u Tương thuộc địa phận c&aacute;c phường, x&atilde; Đ&igrave;nh Bảng, Đồng Nguy&ecirc;n, Tam Sơn, Tương Giang. Thời đ&oacute;, c&aacute;c Vua H&ugrave;ng chia nước Văn Lang th&agrave;nh 15 bộ, Từ Sơn nằm trong bộ Vũ Ninh. Đời nh&agrave; Đường đ&ocirc; hộ, Từ Sơn thuộc địa phận của Long Ch&acirc;u; Thời L&ecirc; Đại H&agrave;nh (989-1005) gọi l&agrave; Cổ ph&aacute;p; Thời nh&agrave; L&yacute; (1010-1400) được đổi th&agrave;nh phủ Thi&ecirc;n Đức; Thời nh&agrave; Trần (1225-1400) được gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dưới thời ph&aacute;p thuộc, ch&iacute;nh quyền thực d&acirc;n tiến h&agrave;nh c&aacute;c cuộc cải c&aacute;ch h&agrave;nh ch&iacute;nh, điều chỉnh địa giới ở một số địa phương. Từ Sơn l&uacute;c đ&oacute; gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n. Năm 1925 đổi lại th&agrave;nh phủ Từ Sơn, thời kỳ n&agrave;y chỉ c&ograve;n lại 10 tổng l&agrave; Dục T&uacute;, Hạ Dương, H&agrave; Lỗ, Hội phụ, Mẫn X&aacute;, Nghĩa Lập, Ph&ugrave; Chẩn, Ph&ugrave; Lưu, Tam Sơn, Y&ecirc;n Thường v&agrave; chỉ quản l&yacute; một huyện Từ Sơn.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sau c&aacute;ch mạng th&aacute;ng 8 năm 1945, c&aacute;c đơn vị h&agrave;nh ch&iacute;nh dưới tỉnh c&oacute; huyện, x&atilde;, b&atilde;i bỏ phủ. Thi h&agrave;nh Quyết định của Ch&iacute;nh phủ ng&agrave;y 08/6/1961 UBHC tỉnh Bắc Ninh đ&atilde; b&agrave;n giao cho UBHC th&agrave;nh phố H&agrave; Nội c&aacute;c x&atilde; thuộc huyện Từ Sơn được cắt về ngoại th&agrave;nh H&agrave; Nội đ&oacute; l&agrave; Li&ecirc;n H&agrave;, V&acirc;n H&agrave;, Mai L&acirc;m, Đ&ocirc;ng Hội, Dục T&uacute;, Đ&igrave;nh Xuy&ecirc;n, Ninh Hiệp, Tiền Phong, TT Y&ecirc;n Vi&ecirc;n, Dương H&agrave;.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Đến ng&agrave;y 14/3/1963, Hội đồng Ch&iacute;nh phủ ra Quyết định số 25/QĐ s&aacute;t nhập hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du th&agrave;nh huyện Ti&ecirc;n Sơn, đồng thời 2 x&atilde; Đ&ocirc;ng Thọ v&agrave; Văn M&ocirc;n được chuyển sang huyện Y&ecirc;n Phong, 2 x&atilde; Tương Giang v&agrave; Ph&uacute; L&acirc;m được chuyển về huyện Ti&ecirc;n Sơn. Ng&agrave;y 9/8/1999 Ch&iacute;nh phủ ra Nghị định số 68/1999/NĐ-CP về việc chia huyện Ti&ecirc;n Sơn th&agrave;nh hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn hiện nay, theo Nghị định số 01/NĐ-CP ng&agrave;y 24/9/2008 của Ch&iacute;nh phủ về việc th&agrave;nh lập thị x&atilde; Từ Sơn, tỉnh Bắc Ninh th&igrave; huyện Từ Sơn được trở th&agrave;nh thị x&atilde; Từ Sơn với 12 đơn vị h&agrave;nh ch&iacute;nh bao gồm: 7 phường, 5 x&atilde; đ&oacute; l&agrave;: phường Đồng Nguy&ecirc;n, T&acirc;n Hồng, Đ&ocirc;ng Ng&agrave;n, Đ&igrave;nh Bảng, Trang Hạ, Đồng Kỵ, Ch&acirc;u Kh&ecirc; v&agrave; c&aacute;c x&atilde; Hương Mạc, Ph&ugrave; Chẩn, Ph&ugrave; Kh&ecirc;, Tam Sơn, Tương Giang.</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thị x&atilde; Từ Sơn c&oacute; diện t&iacute;ch tự nhi&ecirc;n l&agrave; 6.133,23km2, d&acirc;n số tr&ecirc;n 164 ngh&igrave;n người. Địa b&agrave;n thị x&atilde; Từ Sơn nằm ở cửa ng&otilde; ph&iacute;a Bắc của thủ đ&ocirc; H&agrave; Nội, c&oacute; đường quốc lộ, đường sắt huyết mạch giao th&ocirc;ng Từ H&agrave; Nội l&ecirc;n bi&ecirc;n giới Lạng Sơn. Từ trung t&acirc;m thị x&atilde; c&ograve;n c&oacute; nhiều đường bộ nối liền c&aacute;c v&ugrave;ng kinh tế trong v&agrave; ngo&agrave;i tỉnh. Về địa giới h&agrave;nh ch&iacute;nh: ph&iacute;a Bắc gi&aacute;p huyện Y&ecirc;n Phong, ph&iacute;a Đ&ocirc;ng gi&aacute;p huyện Ti&ecirc;n Du, ph&iacute;a T&acirc;y v&agrave; Nam gi&aacute;p c&aacute;c huyện Đ&ocirc;ng Anh, Gia L&acirc;m (H&agrave; Nội).</div>
<div style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: justify;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn c&oacute; nền kinh tế ph&aacute;t triển, ngo&agrave;i sản xuất n&ocirc;ng nghiệp Từ Sơn c&ograve;n c&oacute; rất nhiều l&agrave;ng nghề truyền thống đang ng&agrave;y c&agrave;ng duy tr&igrave; v&agrave; mở rộng như: Đồ gỗ mỹ nghệ Đồng Kỵ, Ph&ugrave; Kh&ecirc;, Hương Mạc, sản xuất sắt th&eacute;p Ch&acirc;u Kh&ecirc;, &nbsp;nghề Dệt ở Tương Giang&hellip; Từ đ&oacute; tạo đ&agrave; cho Từ Sơn chuyển dịch cơ cấu kinh tế với tỷ trọng C&ocirc;ng nghiệp - X&acirc;y dựng cơ bản chiếm 77,9%, dịch vụ 20,1%, n&ocirc;ng nghiệp c&ograve;n 2%, thu nhập b&igrave;nh qu&acirc;n đầu người hiện nay ước đạt 6.370 USD; thu ng&acirc;n s&aacute;ch nh&agrave; nước&nbsp; tr&ecirc;n 670 tỷ đồng. Từ Sơn phấn đấu đạt chuẩn n&ocirc;ng th&ocirc;n mới trong năm 2016. Đ&acirc;y l&agrave; những yếu tố quan trọng để Từ Sơn được chọn l&agrave; một trong những điểm đột ph&aacute; của chiến lược đưa tỉnh Bắc Ninh th&agrave;nh tỉnh c&ocirc;ng nghiệp theo hướng văn minh hiện đại v&agrave;o trước năm 2020./.</div>
<p style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: &quot;times new roman&quot;; font-size: 16px; text-align: right;\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong style=\"margin: 0px; padding: 0px;\">Đ&igrave;nh Minh</strong></p>
',title='Đài phát thanh Từ Sơn | Thời sự tổng hợp',keyword='Đài phát thanh Từ Sơn | Thời sự tổng hợp',description='Đài phát thanh Từ Sơn | Thời sự tổng hợp' where Id=1;
update config set banner='/daituson/view/admin/Themes/kcfinder/upload/images/config/logodaituson.jpg',icon='/daituson/view/admin/Themes/kcfinder/upload/images/config/favicon.jpg',name='Đài phát thanh Từ Sơn | Thời sự tổng hợp',dien_thoai='02413.835.112',fax='02416.260.112',email='phatthanhtuson@gmail.com',tru_so='Khu trung tâm TX Từ Sơn - Bắc Ninh.',giay_phep='Website Đài phát thanh TX Từ Sơn được Bộ TT và TT cấp phép hoạt động theo giấy phép số 116/GP-TTĐT từ tháng 9/2009.',trach_nhiem_chinh='Trưởng Đài - Nguyễn Đình Minh.',trach_nhiem_noi_dung='Phó Trưởng Đài - Nguyễn Thị Châu Loan.',gioi_thieu='<p>
	&nbsp;</p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">Từ Sơn con người - truyền thống văn hiến c&aacute;ch mạng</strong></p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">&nbsp;</strong></p>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Từ Sơn vốn l&agrave; v&ugrave;ng qu&ecirc; gi&agrave;u truyền thống văn hiến v&agrave; c&aacute;ch mạng, qu&ecirc; hương của Vương triều L&yacute; với Đền Đ&ocirc; một di t&iacute;ch lịch sử nổi tiếng. Trải qua bao thế hệ c&ugrave;ng những thăng trầm của lịch sử, nơi đ&acirc;y đ&atilde; sản sinh ra những con người ưu t&uacute; ti&ecirc;u biểu như: Ng&ocirc; Gia Tự - Người chiến sĩ c&aacute;ch mạng lỗi lạc của Đảng ta, Nguyễn Văn Cừ - cố Tổng b&iacute; thư, một tấm gương c&aacute;ch mạng kiệt xuất của Đảng, v&agrave; c&ograve;n nhiều khoa bảng t&agrave;i hoa, đỗ đạt cao l&agrave;m rạng rỡ qu&ecirc; hương đất nước. Người Từ Sơn lu&ocirc;n tự h&agrave;o về điều đ&oacute; v&agrave; kh&ocirc;ng ngừng phấn đấu vươn l&ecirc;n để x&acirc;y dựng qu&ecirc; hương ng&agrave;y c&agrave;ng gi&agrave;u đẹp văn minh.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Theo c&aacute;c nguồn t&agrave;i liệu cổ v&agrave; khảo cổ học từ thời đại H&ugrave;ng Vương, v&ugrave;ng đất Từ Sơn đ&atilde; c&oacute; nhiều bộ tộc người Việt sinh sống dọc theo đ&ocirc;i bờ s&ocirc;ng Ti&ecirc;u Tương thuộc địa phận c&aacute;c phường, x&atilde; Đ&igrave;nh Bảng, Đồng Nguy&ecirc;n, Tam Sơn, Tương Giang. Thời đ&oacute;, c&aacute;c Vua H&ugrave;ng chia nước Văn Lang th&agrave;nh 15 bộ, Từ Sơn nằm trong bộ Vũ Ninh. Đời nh&agrave; Đường đ&ocirc; hộ, Từ Sơn thuộc địa phận của Long Ch&acirc;u; Thời L&ecirc; Đại H&agrave;nh (989-1005) gọi l&agrave; Cổ ph&aacute;p; Thời nh&agrave; L&yacute; (1010-1400) được đổi th&agrave;nh phủ Thi&ecirc;n Đức; Thời nh&agrave; Trần (1225-1400) được gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dưới thời ph&aacute;p thuộc, ch&iacute;nh quyền thực d&acirc;n tiến h&agrave;nh c&aacute;c cuộc cải c&aacute;ch h&agrave;nh ch&iacute;nh, điều chỉnh địa giới ở một số địa phương. Từ Sơn l&uacute;c đ&oacute; gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n. Năm 1925 đổi lại th&agrave;nh phủ Từ Sơn, thời kỳ n&agrave;y chỉ c&ograve;n lại 10 tổng l&agrave; Dục T&uacute;, Hạ Dương, H&agrave; Lỗ, Hội phụ, Mẫn X&aacute;, Nghĩa Lập, Ph&ugrave; Chẩn, Ph&ugrave; Lưu, Tam Sơn, Y&ecirc;n Thường v&agrave; chỉ quản l&yacute; một huyện Từ Sơn.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sau c&aacute;ch mạng th&aacute;ng 8 năm 1945, c&aacute;c đơn vị h&agrave;nh ch&iacute;nh dưới tỉnh c&oacute; huyện, x&atilde;, b&atilde;i bỏ phủ. Thi h&agrave;nh Quyết định của Ch&iacute;nh phủ ng&agrave;y 08/6/1961 UBHC tỉnh Bắc Ninh đ&atilde; b&agrave;n giao cho UBHC th&agrave;nh phố H&agrave; Nội c&aacute;c x&atilde; thuộc huyện Từ Sơn được cắt về ngoại th&agrave;nh H&agrave; Nội đ&oacute; l&agrave; Li&ecirc;n H&agrave;, V&acirc;n H&agrave;, Mai L&acirc;m, Đ&ocirc;ng Hội, Dục T&uacute;, Đ&igrave;nh Xuy&ecirc;n, Ninh Hiệp, Tiền Phong, TT Y&ecirc;n Vi&ecirc;n, Dương H&agrave;.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Đến ng&agrave;y 14/3/1963, Hội đồng Ch&iacute;nh phủ ra Quyết định số 25/QĐ s&aacute;t nhập hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du th&agrave;nh huyện Ti&ecirc;n Sơn, đồng thời 2 x&atilde; Đ&ocirc;ng Thọ v&agrave; Văn M&ocirc;n được chuyển sang huyện Y&ecirc;n Phong, 2 x&atilde; Tương Giang v&agrave; Ph&uacute; L&acirc;m được chuyển về huyện Ti&ecirc;n Sơn. Ng&agrave;y 9/8/1999 Ch&iacute;nh phủ ra Nghị định số 68/1999/NĐ-CP về việc chia huyện Ti&ecirc;n Sơn th&agrave;nh hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn hiện nay, theo Nghị định số 01/NĐ-CP ng&agrave;y 24/9/2008 của Ch&iacute;nh phủ về việc th&agrave;nh lập thị x&atilde; Từ Sơn, tỉnh Bắc Ninh th&igrave; huyện Từ Sơn được trở th&agrave;nh thị x&atilde; Từ Sơn với 12 đơn vị h&agrave;nh ch&iacute;nh bao gồm: 7 phường, 5 x&atilde; đ&oacute; l&agrave;: phường Đồng Nguy&ecirc;n, T&acirc;n Hồng, Đ&ocirc;ng Ng&agrave;n, Đ&igrave;nh Bảng, Trang Hạ, Đồng Kỵ, Ch&acirc;u Kh&ecirc; v&agrave; c&aacute;c x&atilde; Hương Mạc, Ph&ugrave; Chẩn, Ph&ugrave; Kh&ecirc;, Tam Sơn, Tương Giang.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thị x&atilde; Từ Sơn c&oacute; diện t&iacute;ch tự nhi&ecirc;n l&agrave; 6.133,23km2, d&acirc;n số tr&ecirc;n 164 ngh&igrave;n người. Địa b&agrave;n thị x&atilde; Từ Sơn nằm ở cửa ng&otilde; ph&iacute;a Bắc của thủ đ&ocirc; H&agrave; Nội, c&oacute; đường quốc lộ, đường sắt huyết mạch giao th&ocirc;ng Từ H&agrave; Nội l&ecirc;n bi&ecirc;n giới Lạng Sơn. Từ trung t&acirc;m thị x&atilde; c&ograve;n c&oacute; nhiều đường bộ nối liền c&aacute;c v&ugrave;ng kinh tế trong v&agrave; ngo&agrave;i tỉnh. Về địa giới h&agrave;nh ch&iacute;nh: ph&iacute;a Bắc gi&aacute;p huyện Y&ecirc;n Phong, ph&iacute;a Đ&ocirc;ng gi&aacute;p huyện Ti&ecirc;n Du, ph&iacute;a T&acirc;y v&agrave; Nam gi&aacute;p c&aacute;c huyện Đ&ocirc;ng Anh, Gia L&acirc;m (H&agrave; Nội).</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn c&oacute; nền kinh tế ph&aacute;t triển, ngo&agrave;i sản xuất n&ocirc;ng nghiệp Từ Sơn c&ograve;n c&oacute; rất nhiều l&agrave;ng nghề truyền thống đang ng&agrave;y c&agrave;ng duy tr&igrave; v&agrave; mở rộng như: Đồ gỗ mỹ nghệ Đồng Kỵ, Ph&ugrave; Kh&ecirc;, Hương Mạc, sản xuất sắt th&eacute;p Ch&acirc;u Kh&ecirc;, &nbsp;nghề Dệt ở Tương Giang&hellip; Từ đ&oacute; tạo đ&agrave; cho Từ Sơn chuyển dịch cơ cấu kinh tế với tỷ trọng C&ocirc;ng nghiệp - X&acirc;y dựng cơ bản chiếm 77,9%, dịch vụ 20,1%, n&ocirc;ng nghiệp c&ograve;n 2%, thu nhập b&igrave;nh qu&acirc;n đầu người hiện nay ước đạt 6.370 USD; thu ng&acirc;n s&aacute;ch nh&agrave; nước&nbsp; tr&ecirc;n 670 tỷ đồng. Từ Sơn phấn đấu đạt chuẩn n&ocirc;ng th&ocirc;n mới trong năm 2016. Đ&acirc;y l&agrave; những yếu tố quan trọng để Từ Sơn được chọn l&agrave; một trong những điểm đột ph&aacute; của chiến lược đưa tỉnh Bắc Ninh th&agrave;nh tỉnh c&ocirc;ng nghiệp theo hướng văn minh hiện đại v&agrave;o trước năm 2020./.</div>
<p font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong style=\"margin: 0px; padding: 0px;\">Đ&igrave;nh Minh</strong></p>
',title='Đài phát thanh Từ Sơn | Thời sự tổng hợp',keyword='Đài phát thanh Từ Sơn | Thời sự tổng hợp',description='Đài phát thanh Từ Sơn | Thời sự tổng hợp' where Id=1;
update config set banner='/daituson/view/admin/Themes/kcfinder/upload/images/config/logodaituson.jpg',icon='/daituson/view/admin/Themes/kcfinder/upload/images/config/favicon.jpg',name='Đài phát thanh Từ Sơn | Thời sự tổng hợp',dien_thoai='02413.835.112',fax='02416.260.112',email='phatthanhtuson@gmail.com',tru_so='Khu trung tâm TX Từ Sơn - Bắc Ninh.',giay_phep='Website Đài phát thanh TX Từ Sơn được Bộ TT và TT cấp phép hoạt động theo giấy phép số 116/GP-TTĐT từ tháng 9/2009.',trach_nhiem_chinh='Trưởng Đài - Nguyễn Đình Minh.',trach_nhiem_noi_dung='Phó Trưởng Đài - Nguyễn Thị Châu Loan.',slide_text='Đảng bộ, chính quyền và nhân dân thị xã Từ Sơn Quyết tâm thực hiện thắng lợi nghị quyết Đại hội Đảng bộ thị xã lần thứ XVII, Nghị quyết Đại hội Đảng bộ tỉnh lần thứ XIX, Nghị quyết Đại hội lần thứ XII của Đảng !',gioi_thieu='<p>
	&nbsp;</p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">Từ Sơn con người - truyền thống văn hiến c&aacute;ch mạng</strong></p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">&nbsp;</strong></p>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Từ Sơn vốn l&agrave; v&ugrave;ng qu&ecirc; gi&agrave;u truyền thống văn hiến v&agrave; c&aacute;ch mạng, qu&ecirc; hương của Vương triều L&yacute; với Đền Đ&ocirc; một di t&iacute;ch lịch sử nổi tiếng. Trải qua bao thế hệ c&ugrave;ng những thăng trầm của lịch sử, nơi đ&acirc;y đ&atilde; sản sinh ra những con người ưu t&uacute; ti&ecirc;u biểu như: Ng&ocirc; Gia Tự - Người chiến sĩ c&aacute;ch mạng lỗi lạc của Đảng ta, Nguyễn Văn Cừ - cố Tổng b&iacute; thư, một tấm gương c&aacute;ch mạng kiệt xuất của Đảng, v&agrave; c&ograve;n nhiều khoa bảng t&agrave;i hoa, đỗ đạt cao l&agrave;m rạng rỡ qu&ecirc; hương đất nước. Người Từ Sơn lu&ocirc;n tự h&agrave;o về điều đ&oacute; v&agrave; kh&ocirc;ng ngừng phấn đấu vươn l&ecirc;n để x&acirc;y dựng qu&ecirc; hương ng&agrave;y c&agrave;ng gi&agrave;u đẹp văn minh.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Theo c&aacute;c nguồn t&agrave;i liệu cổ v&agrave; khảo cổ học từ thời đại H&ugrave;ng Vương, v&ugrave;ng đất Từ Sơn đ&atilde; c&oacute; nhiều bộ tộc người Việt sinh sống dọc theo đ&ocirc;i bờ s&ocirc;ng Ti&ecirc;u Tương thuộc địa phận c&aacute;c phường, x&atilde; Đ&igrave;nh Bảng, Đồng Nguy&ecirc;n, Tam Sơn, Tương Giang. Thời đ&oacute;, c&aacute;c Vua H&ugrave;ng chia nước Văn Lang th&agrave;nh 15 bộ, Từ Sơn nằm trong bộ Vũ Ninh. Đời nh&agrave; Đường đ&ocirc; hộ, Từ Sơn thuộc địa phận của Long Ch&acirc;u; Thời L&ecirc; Đại H&agrave;nh (989-1005) gọi l&agrave; Cổ ph&aacute;p; Thời nh&agrave; L&yacute; (1010-1400) được đổi th&agrave;nh phủ Thi&ecirc;n Đức; Thời nh&agrave; Trần (1225-1400) được gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dưới thời ph&aacute;p thuộc, ch&iacute;nh quyền thực d&acirc;n tiến h&agrave;nh c&aacute;c cuộc cải c&aacute;ch h&agrave;nh ch&iacute;nh, điều chỉnh địa giới ở một số địa phương. Từ Sơn l&uacute;c đ&oacute; gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n. Năm 1925 đổi lại th&agrave;nh phủ Từ Sơn, thời kỳ n&agrave;y chỉ c&ograve;n lại 10 tổng l&agrave; Dục T&uacute;, Hạ Dương, H&agrave; Lỗ, Hội phụ, Mẫn X&aacute;, Nghĩa Lập, Ph&ugrave; Chẩn, Ph&ugrave; Lưu, Tam Sơn, Y&ecirc;n Thường v&agrave; chỉ quản l&yacute; một huyện Từ Sơn.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sau c&aacute;ch mạng th&aacute;ng 8 năm 1945, c&aacute;c đơn vị h&agrave;nh ch&iacute;nh dưới tỉnh c&oacute; huyện, x&atilde;, b&atilde;i bỏ phủ. Thi h&agrave;nh Quyết định của Ch&iacute;nh phủ ng&agrave;y 08/6/1961 UBHC tỉnh Bắc Ninh đ&atilde; b&agrave;n giao cho UBHC th&agrave;nh phố H&agrave; Nội c&aacute;c x&atilde; thuộc huyện Từ Sơn được cắt về ngoại th&agrave;nh H&agrave; Nội đ&oacute; l&agrave; Li&ecirc;n H&agrave;, V&acirc;n H&agrave;, Mai L&acirc;m, Đ&ocirc;ng Hội, Dục T&uacute;, Đ&igrave;nh Xuy&ecirc;n, Ninh Hiệp, Tiền Phong, TT Y&ecirc;n Vi&ecirc;n, Dương H&agrave;.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Đến ng&agrave;y 14/3/1963, Hội đồng Ch&iacute;nh phủ ra Quyết định số 25/QĐ s&aacute;t nhập hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du th&agrave;nh huyện Ti&ecirc;n Sơn, đồng thời 2 x&atilde; Đ&ocirc;ng Thọ v&agrave; Văn M&ocirc;n được chuyển sang huyện Y&ecirc;n Phong, 2 x&atilde; Tương Giang v&agrave; Ph&uacute; L&acirc;m được chuyển về huyện Ti&ecirc;n Sơn. Ng&agrave;y 9/8/1999 Ch&iacute;nh phủ ra Nghị định số 68/1999/NĐ-CP về việc chia huyện Ti&ecirc;n Sơn th&agrave;nh hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn hiện nay, theo Nghị định số 01/NĐ-CP ng&agrave;y 24/9/2008 của Ch&iacute;nh phủ về việc th&agrave;nh lập thị x&atilde; Từ Sơn, tỉnh Bắc Ninh th&igrave; huyện Từ Sơn được trở th&agrave;nh thị x&atilde; Từ Sơn với 12 đơn vị h&agrave;nh ch&iacute;nh bao gồm: 7 phường, 5 x&atilde; đ&oacute; l&agrave;: phường Đồng Nguy&ecirc;n, T&acirc;n Hồng, Đ&ocirc;ng Ng&agrave;n, Đ&igrave;nh Bảng, Trang Hạ, Đồng Kỵ, Ch&acirc;u Kh&ecirc; v&agrave; c&aacute;c x&atilde; Hương Mạc, Ph&ugrave; Chẩn, Ph&ugrave; Kh&ecirc;, Tam Sơn, Tương Giang.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thị x&atilde; Từ Sơn c&oacute; diện t&iacute;ch tự nhi&ecirc;n l&agrave; 6.133,23km2, d&acirc;n số tr&ecirc;n 164 ngh&igrave;n người. Địa b&agrave;n thị x&atilde; Từ Sơn nằm ở cửa ng&otilde; ph&iacute;a Bắc của thủ đ&ocirc; H&agrave; Nội, c&oacute; đường quốc lộ, đường sắt huyết mạch giao th&ocirc;ng Từ H&agrave; Nội l&ecirc;n bi&ecirc;n giới Lạng Sơn. Từ trung t&acirc;m thị x&atilde; c&ograve;n c&oacute; nhiều đường bộ nối liền c&aacute;c v&ugrave;ng kinh tế trong v&agrave; ngo&agrave;i tỉnh. Về địa giới h&agrave;nh ch&iacute;nh: ph&iacute;a Bắc gi&aacute;p huyện Y&ecirc;n Phong, ph&iacute;a Đ&ocirc;ng gi&aacute;p huyện Ti&ecirc;n Du, ph&iacute;a T&acirc;y v&agrave; Nam gi&aacute;p c&aacute;c huyện Đ&ocirc;ng Anh, Gia L&acirc;m (H&agrave; Nội).</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn c&oacute; nền kinh tế ph&aacute;t triển, ngo&agrave;i sản xuất n&ocirc;ng nghiệp Từ Sơn c&ograve;n c&oacute; rất nhiều l&agrave;ng nghề truyền thống đang ng&agrave;y c&agrave;ng duy tr&igrave; v&agrave; mở rộng như: Đồ gỗ mỹ nghệ Đồng Kỵ, Ph&ugrave; Kh&ecirc;, Hương Mạc, sản xuất sắt th&eacute;p Ch&acirc;u Kh&ecirc;, &nbsp;nghề Dệt ở Tương Giang&hellip; Từ đ&oacute; tạo đ&agrave; cho Từ Sơn chuyển dịch cơ cấu kinh tế với tỷ trọng C&ocirc;ng nghiệp - X&acirc;y dựng cơ bản chiếm 77,9%, dịch vụ 20,1%, n&ocirc;ng nghiệp c&ograve;n 2%, thu nhập b&igrave;nh qu&acirc;n đầu người hiện nay ước đạt 6.370 USD; thu ng&acirc;n s&aacute;ch nh&agrave; nước&nbsp; tr&ecirc;n 670 tỷ đồng. Từ Sơn phấn đấu đạt chuẩn n&ocirc;ng th&ocirc;n mới trong năm 2016. Đ&acirc;y l&agrave; những yếu tố quan trọng để Từ Sơn được chọn l&agrave; một trong những điểm đột ph&aacute; của chiến lược đưa tỉnh Bắc Ninh th&agrave;nh tỉnh c&ocirc;ng nghiệp theo hướng văn minh hiện đại v&agrave;o trước năm 2020./.</div>
<p font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong style=\"margin: 0px; padding: 0px;\">Đ&igrave;nh Minh</strong></p>
',title='Đài phát thanh Từ Sơn | Thời sự tổng hợp',keyword='Đài phát thanh Từ Sơn | Thời sự tổng hợp',description='Đài phát thanh Từ Sơn | Thời sự tổng hợp' where Id=1;
update config set banner='/daituson/view/admin/Themes/kcfinder/upload/images/config/logodaituson.jpg',icon='/daituson/view/admin/Themes/kcfinder/upload/images/config/favicon.jpg',name='Đài phát thanh Từ Sơn | Thời sự tổng hợp',dien_thoai='02413.835.1128',fax='02416.260.112',email='phatthanhtuson@gmail.com',tru_so='Khu trung tâm TX Từ Sơn - Bắc Ninh.',giay_phep='Website Đài phát thanh TX Từ Sơn được Bộ TT và TT cấp phép hoạt động theo giấy phép số 116/GP-TTĐT từ tháng 9/2009.',trach_nhiem_chinh='Trưởng Đài - Nguyễn Đình Minh.',trach_nhiem_noi_dung='Phó Trưởng Đài - Nguyễn Thị Châu Loan.',slide_text='Đảng bộ, chính quyền và nhân dân thị xã Từ Sơn Quyết tâm thực hiện thắng lợi nghị quyết Đại hội Đảng bộ thị xã lần thứ XVII, Nghị quyết Đại hội Đảng bộ tỉnh lần thứ XIX, Nghị quyết Đại hội lần thứ XII của Đảng !',gioi_thieu='<p>
	&nbsp;</p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">Từ Sơn con người - truyền thống văn hiến c&aacute;ch mạng</strong></p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">&nbsp;</strong></p>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Từ Sơn vốn l&agrave; v&ugrave;ng qu&ecirc; gi&agrave;u truyền thống văn hiến v&agrave; c&aacute;ch mạng, qu&ecirc; hương của Vương triều L&yacute; với Đền Đ&ocirc; một di t&iacute;ch lịch sử nổi tiếng. Trải qua bao thế hệ c&ugrave;ng những thăng trầm của lịch sử, nơi đ&acirc;y đ&atilde; sản sinh ra những con người ưu t&uacute; ti&ecirc;u biểu như: Ng&ocirc; Gia Tự - Người chiến sĩ c&aacute;ch mạng lỗi lạc của Đảng ta, Nguyễn Văn Cừ - cố Tổng b&iacute; thư, một tấm gương c&aacute;ch mạng kiệt xuất của Đảng, v&agrave; c&ograve;n nhiều khoa bảng t&agrave;i hoa, đỗ đạt cao l&agrave;m rạng rỡ qu&ecirc; hương đất nước. Người Từ Sơn lu&ocirc;n tự h&agrave;o về điều đ&oacute; v&agrave; kh&ocirc;ng ngừng phấn đấu vươn l&ecirc;n để x&acirc;y dựng qu&ecirc; hương ng&agrave;y c&agrave;ng gi&agrave;u đẹp văn minh.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Theo c&aacute;c nguồn t&agrave;i liệu cổ v&agrave; khảo cổ học từ thời đại H&ugrave;ng Vương, v&ugrave;ng đất Từ Sơn đ&atilde; c&oacute; nhiều bộ tộc người Việt sinh sống dọc theo đ&ocirc;i bờ s&ocirc;ng Ti&ecirc;u Tương thuộc địa phận c&aacute;c phường, x&atilde; Đ&igrave;nh Bảng, Đồng Nguy&ecirc;n, Tam Sơn, Tương Giang. Thời đ&oacute;, c&aacute;c Vua H&ugrave;ng chia nước Văn Lang th&agrave;nh 15 bộ, Từ Sơn nằm trong bộ Vũ Ninh. Đời nh&agrave; Đường đ&ocirc; hộ, Từ Sơn thuộc địa phận của Long Ch&acirc;u; Thời L&ecirc; Đại H&agrave;nh (989-1005) gọi l&agrave; Cổ ph&aacute;p; Thời nh&agrave; L&yacute; (1010-1400) được đổi th&agrave;nh phủ Thi&ecirc;n Đức; Thời nh&agrave; Trần (1225-1400) được gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dưới thời ph&aacute;p thuộc, ch&iacute;nh quyền thực d&acirc;n tiến h&agrave;nh c&aacute;c cuộc cải c&aacute;ch h&agrave;nh ch&iacute;nh, điều chỉnh địa giới ở một số địa phương. Từ Sơn l&uacute;c đ&oacute; gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n. Năm 1925 đổi lại th&agrave;nh phủ Từ Sơn, thời kỳ n&agrave;y chỉ c&ograve;n lại 10 tổng l&agrave; Dục T&uacute;, Hạ Dương, H&agrave; Lỗ, Hội phụ, Mẫn X&aacute;, Nghĩa Lập, Ph&ugrave; Chẩn, Ph&ugrave; Lưu, Tam Sơn, Y&ecirc;n Thường v&agrave; chỉ quản l&yacute; một huyện Từ Sơn.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sau c&aacute;ch mạng th&aacute;ng 8 năm 1945, c&aacute;c đơn vị h&agrave;nh ch&iacute;nh dưới tỉnh c&oacute; huyện, x&atilde;, b&atilde;i bỏ phủ. Thi h&agrave;nh Quyết định của Ch&iacute;nh phủ ng&agrave;y 08/6/1961 UBHC tỉnh Bắc Ninh đ&atilde; b&agrave;n giao cho UBHC th&agrave;nh phố H&agrave; Nội c&aacute;c x&atilde; thuộc huyện Từ Sơn được cắt về ngoại th&agrave;nh H&agrave; Nội đ&oacute; l&agrave; Li&ecirc;n H&agrave;, V&acirc;n H&agrave;, Mai L&acirc;m, Đ&ocirc;ng Hội, Dục T&uacute;, Đ&igrave;nh Xuy&ecirc;n, Ninh Hiệp, Tiền Phong, TT Y&ecirc;n Vi&ecirc;n, Dương H&agrave;.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Đến ng&agrave;y 14/3/1963, Hội đồng Ch&iacute;nh phủ ra Quyết định số 25/QĐ s&aacute;t nhập hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du th&agrave;nh huyện Ti&ecirc;n Sơn, đồng thời 2 x&atilde; Đ&ocirc;ng Thọ v&agrave; Văn M&ocirc;n được chuyển sang huyện Y&ecirc;n Phong, 2 x&atilde; Tương Giang v&agrave; Ph&uacute; L&acirc;m được chuyển về huyện Ti&ecirc;n Sơn. Ng&agrave;y 9/8/1999 Ch&iacute;nh phủ ra Nghị định số 68/1999/NĐ-CP về việc chia huyện Ti&ecirc;n Sơn th&agrave;nh hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn hiện nay, theo Nghị định số 01/NĐ-CP ng&agrave;y 24/9/2008 của Ch&iacute;nh phủ về việc th&agrave;nh lập thị x&atilde; Từ Sơn, tỉnh Bắc Ninh th&igrave; huyện Từ Sơn được trở th&agrave;nh thị x&atilde; Từ Sơn với 12 đơn vị h&agrave;nh ch&iacute;nh bao gồm: 7 phường, 5 x&atilde; đ&oacute; l&agrave;: phường Đồng Nguy&ecirc;n, T&acirc;n Hồng, Đ&ocirc;ng Ng&agrave;n, Đ&igrave;nh Bảng, Trang Hạ, Đồng Kỵ, Ch&acirc;u Kh&ecirc; v&agrave; c&aacute;c x&atilde; Hương Mạc, Ph&ugrave; Chẩn, Ph&ugrave; Kh&ecirc;, Tam Sơn, Tương Giang.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thị x&atilde; Từ Sơn c&oacute; diện t&iacute;ch tự nhi&ecirc;n l&agrave; 6.133,23km2, d&acirc;n số tr&ecirc;n 164 ngh&igrave;n người. Địa b&agrave;n thị x&atilde; Từ Sơn nằm ở cửa ng&otilde; ph&iacute;a Bắc của thủ đ&ocirc; H&agrave; Nội, c&oacute; đường quốc lộ, đường sắt huyết mạch giao th&ocirc;ng Từ H&agrave; Nội l&ecirc;n bi&ecirc;n giới Lạng Sơn. Từ trung t&acirc;m thị x&atilde; c&ograve;n c&oacute; nhiều đường bộ nối liền c&aacute;c v&ugrave;ng kinh tế trong v&agrave; ngo&agrave;i tỉnh. Về địa giới h&agrave;nh ch&iacute;nh: ph&iacute;a Bắc gi&aacute;p huyện Y&ecirc;n Phong, ph&iacute;a Đ&ocirc;ng gi&aacute;p huyện Ti&ecirc;n Du, ph&iacute;a T&acirc;y v&agrave; Nam gi&aacute;p c&aacute;c huyện Đ&ocirc;ng Anh, Gia L&acirc;m (H&agrave; Nội).</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn c&oacute; nền kinh tế ph&aacute;t triển, ngo&agrave;i sản xuất n&ocirc;ng nghiệp Từ Sơn c&ograve;n c&oacute; rất nhiều l&agrave;ng nghề truyền thống đang ng&agrave;y c&agrave;ng duy tr&igrave; v&agrave; mở rộng như: Đồ gỗ mỹ nghệ Đồng Kỵ, Ph&ugrave; Kh&ecirc;, Hương Mạc, sản xuất sắt th&eacute;p Ch&acirc;u Kh&ecirc;, &nbsp;nghề Dệt ở Tương Giang&hellip; Từ đ&oacute; tạo đ&agrave; cho Từ Sơn chuyển dịch cơ cấu kinh tế với tỷ trọng C&ocirc;ng nghiệp - X&acirc;y dựng cơ bản chiếm 77,9%, dịch vụ 20,1%, n&ocirc;ng nghiệp c&ograve;n 2%, thu nhập b&igrave;nh qu&acirc;n đầu người hiện nay ước đạt 6.370 USD; thu ng&acirc;n s&aacute;ch nh&agrave; nước&nbsp; tr&ecirc;n 670 tỷ đồng. Từ Sơn phấn đấu đạt chuẩn n&ocirc;ng th&ocirc;n mới trong năm 2016. Đ&acirc;y l&agrave; những yếu tố quan trọng để Từ Sơn được chọn l&agrave; một trong những điểm đột ph&aacute; của chiến lược đưa tỉnh Bắc Ninh th&agrave;nh tỉnh c&ocirc;ng nghiệp theo hướng văn minh hiện đại v&agrave;o trước năm 2020./.</div>
<p font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong style=\"margin: 0px; padding: 0px;\">Đ&igrave;nh Minh</strong></p>
',title='Đài phát thanh Từ Sơn | Thời sự tổng hợp',keyword='Đài phát thanh Từ Sơn | Thời sự tổng hợp',description='Đài phát thanh Từ Sơn | Thời sự tổng hợp' where Id=1;
update config set banner='/daituson/view/admin/Themes/kcfinder/upload/images/config/logodaituson.jpg',icon='/daituson/view/admin/Themes/kcfinder/upload/images/config/favicon.jpg',name='Đài phát thanh Từ Sơn | Thời sự tổng hợp',dien_thoai='02413.835.112',fax='02416.260.112',email='phatthanhtuson@gmail.com',tru_so='Khu trung tâm TX Từ Sơn - Bắc Ninh.',giay_phep='Website Đài phát thanh TX Từ Sơn được Bộ TT và TT cấp phép hoạt động theo giấy phép số 116/GP-TTĐT từ tháng 9/2009.',trach_nhiem_chinh='Trưởng Đài - Nguyễn Đình Minh.',trach_nhiem_noi_dung='Phó Trưởng Đài - Nguyễn Thị Châu Loan.',slide_text='Đảng bộ, chính quyền và nhân dân thị xã Từ Sơn Quyết tâm thực hiện thắng lợi nghị quyết Đại hội Đảng bộ thị xã lần thứ XVII, Nghị quyết Đại hội Đảng bộ tỉnh lần thứ XIX, Nghị quyết Đại hội lần thứ XII của Đảng !',gioi_thieu='<p>
	&nbsp;</p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">Từ Sơn con người - truyền thống văn hiến c&aacute;ch mạng</strong></p>
<p align=\"center\" font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" times=\"\">
	<strong style=\"margin: 0px; padding: 0px;\">&nbsp;</strong></p>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Từ Sơn vốn l&agrave; v&ugrave;ng qu&ecirc; gi&agrave;u truyền thống văn hiến v&agrave; c&aacute;ch mạng, qu&ecirc; hương của Vương triều L&yacute; với Đền Đ&ocirc; một di t&iacute;ch lịch sử nổi tiếng. Trải qua bao thế hệ c&ugrave;ng những thăng trầm của lịch sử, nơi đ&acirc;y đ&atilde; sản sinh ra những con người ưu t&uacute; ti&ecirc;u biểu như: Ng&ocirc; Gia Tự - Người chiến sĩ c&aacute;ch mạng lỗi lạc của Đảng ta, Nguyễn Văn Cừ - cố Tổng b&iacute; thư, một tấm gương c&aacute;ch mạng kiệt xuất của Đảng, v&agrave; c&ograve;n nhiều khoa bảng t&agrave;i hoa, đỗ đạt cao l&agrave;m rạng rỡ qu&ecirc; hương đất nước. Người Từ Sơn lu&ocirc;n tự h&agrave;o về điều đ&oacute; v&agrave; kh&ocirc;ng ngừng phấn đấu vươn l&ecirc;n để x&acirc;y dựng qu&ecirc; hương ng&agrave;y c&agrave;ng gi&agrave;u đẹp văn minh.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Theo c&aacute;c nguồn t&agrave;i liệu cổ v&agrave; khảo cổ học từ thời đại H&ugrave;ng Vương, v&ugrave;ng đất Từ Sơn đ&atilde; c&oacute; nhiều bộ tộc người Việt sinh sống dọc theo đ&ocirc;i bờ s&ocirc;ng Ti&ecirc;u Tương thuộc địa phận c&aacute;c phường, x&atilde; Đ&igrave;nh Bảng, Đồng Nguy&ecirc;n, Tam Sơn, Tương Giang. Thời đ&oacute;, c&aacute;c Vua H&ugrave;ng chia nước Văn Lang th&agrave;nh 15 bộ, Từ Sơn nằm trong bộ Vũ Ninh. Đời nh&agrave; Đường đ&ocirc; hộ, Từ Sơn thuộc địa phận của Long Ch&acirc;u; Thời L&ecirc; Đại H&agrave;nh (989-1005) gọi l&agrave; Cổ ph&aacute;p; Thời nh&agrave; L&yacute; (1010-1400) được đổi th&agrave;nh phủ Thi&ecirc;n Đức; Thời nh&agrave; Trần (1225-1400) được gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dưới thời ph&aacute;p thuộc, ch&iacute;nh quyền thực d&acirc;n tiến h&agrave;nh c&aacute;c cuộc cải c&aacute;ch h&agrave;nh ch&iacute;nh, điều chỉnh địa giới ở một số địa phương. Từ Sơn l&uacute;c đ&oacute; gọi l&agrave; huyện Đ&ocirc;ng Ng&agrave;n. Năm 1925 đổi lại th&agrave;nh phủ Từ Sơn, thời kỳ n&agrave;y chỉ c&ograve;n lại 10 tổng l&agrave; Dục T&uacute;, Hạ Dương, H&agrave; Lỗ, Hội phụ, Mẫn X&aacute;, Nghĩa Lập, Ph&ugrave; Chẩn, Ph&ugrave; Lưu, Tam Sơn, Y&ecirc;n Thường v&agrave; chỉ quản l&yacute; một huyện Từ Sơn.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sau c&aacute;ch mạng th&aacute;ng 8 năm 1945, c&aacute;c đơn vị h&agrave;nh ch&iacute;nh dưới tỉnh c&oacute; huyện, x&atilde;, b&atilde;i bỏ phủ. Thi h&agrave;nh Quyết định của Ch&iacute;nh phủ ng&agrave;y 08/6/1961 UBHC tỉnh Bắc Ninh đ&atilde; b&agrave;n giao cho UBHC th&agrave;nh phố H&agrave; Nội c&aacute;c x&atilde; thuộc huyện Từ Sơn được cắt về ngoại th&agrave;nh H&agrave; Nội đ&oacute; l&agrave; Li&ecirc;n H&agrave;, V&acirc;n H&agrave;, Mai L&acirc;m, Đ&ocirc;ng Hội, Dục T&uacute;, Đ&igrave;nh Xuy&ecirc;n, Ninh Hiệp, Tiền Phong, TT Y&ecirc;n Vi&ecirc;n, Dương H&agrave;.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Đến ng&agrave;y 14/3/1963, Hội đồng Ch&iacute;nh phủ ra Quyết định số 25/QĐ s&aacute;t nhập hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du th&agrave;nh huyện Ti&ecirc;n Sơn, đồng thời 2 x&atilde; Đ&ocirc;ng Thọ v&agrave; Văn M&ocirc;n được chuyển sang huyện Y&ecirc;n Phong, 2 x&atilde; Tương Giang v&agrave; Ph&uacute; L&acirc;m được chuyển về huyện Ti&ecirc;n Sơn. Ng&agrave;y 9/8/1999 Ch&iacute;nh phủ ra Nghị định số 68/1999/NĐ-CP về việc chia huyện Ti&ecirc;n Sơn th&agrave;nh hai huyện Từ Sơn v&agrave; Ti&ecirc;n Du.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn hiện nay, theo Nghị định số 01/NĐ-CP ng&agrave;y 24/9/2008 của Ch&iacute;nh phủ về việc th&agrave;nh lập thị x&atilde; Từ Sơn, tỉnh Bắc Ninh th&igrave; huyện Từ Sơn được trở th&agrave;nh thị x&atilde; Từ Sơn với 12 đơn vị h&agrave;nh ch&iacute;nh bao gồm: 7 phường, 5 x&atilde; đ&oacute; l&agrave;: phường Đồng Nguy&ecirc;n, T&acirc;n Hồng, Đ&ocirc;ng Ng&agrave;n, Đ&igrave;nh Bảng, Trang Hạ, Đồng Kỵ, Ch&acirc;u Kh&ecirc; v&agrave; c&aacute;c x&atilde; Hương Mạc, Ph&ugrave; Chẩn, Ph&ugrave; Kh&ecirc;, Tam Sơn, Tương Giang.</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thị x&atilde; Từ Sơn c&oacute; diện t&iacute;ch tự nhi&ecirc;n l&agrave; 6.133,23km2, d&acirc;n số tr&ecirc;n 164 ngh&igrave;n người. Địa b&agrave;n thị x&atilde; Từ Sơn nằm ở cửa ng&otilde; ph&iacute;a Bắc của thủ đ&ocirc; H&agrave; Nội, c&oacute; đường quốc lộ, đường sắt huyết mạch giao th&ocirc;ng Từ H&agrave; Nội l&ecirc;n bi&ecirc;n giới Lạng Sơn. Từ trung t&acirc;m thị x&atilde; c&ograve;n c&oacute; nhiều đường bộ nối liền c&aacute;c v&ugrave;ng kinh tế trong v&agrave; ngo&agrave;i tỉnh. Về địa giới h&agrave;nh ch&iacute;nh: ph&iacute;a Bắc gi&aacute;p huyện Y&ecirc;n Phong, ph&iacute;a Đ&ocirc;ng gi&aacute;p huyện Ti&ecirc;n Du, ph&iacute;a T&acirc;y v&agrave; Nam gi&aacute;p c&aacute;c huyện Đ&ocirc;ng Anh, Gia L&acirc;m (H&agrave; Nội).</div>
<div font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ Sơn c&oacute; nền kinh tế ph&aacute;t triển, ngo&agrave;i sản xuất n&ocirc;ng nghiệp Từ Sơn c&ograve;n c&oacute; rất nhiều l&agrave;ng nghề truyền thống đang ng&agrave;y c&agrave;ng duy tr&igrave; v&agrave; mở rộng như: Đồ gỗ mỹ nghệ Đồng Kỵ, Ph&ugrave; Kh&ecirc;, Hương Mạc, sản xuất sắt th&eacute;p Ch&acirc;u Kh&ecirc;, &nbsp;nghề Dệt ở Tương Giang&hellip; Từ đ&oacute; tạo đ&agrave; cho Từ Sơn chuyển dịch cơ cấu kinh tế với tỷ trọng C&ocirc;ng nghiệp - X&acirc;y dựng cơ bản chiếm 77,9%, dịch vụ 20,1%, n&ocirc;ng nghiệp c&ograve;n 2%, thu nhập b&igrave;nh qu&acirc;n đầu người hiện nay ước đạt 6.370 USD; thu ng&acirc;n s&aacute;ch nh&agrave; nước&nbsp; tr&ecirc;n 670 tỷ đồng. Từ Sơn phấn đấu đạt chuẩn n&ocirc;ng th&ocirc;n mới trong năm 2016. Đ&acirc;y l&agrave; những yếu tố quan trọng để Từ Sơn được chọn l&agrave; một trong những điểm đột ph&aacute; của chiến lược đưa tỉnh Bắc Ninh th&agrave;nh tỉnh c&ocirc;ng nghiệp theo hướng văn minh hiện đại v&agrave;o trước năm 2020./.</div>
<p font-size:=\"\" new=\"\" style=\"margin: 0px; padding: 0px; color: rgb(60, 59, 59); font-family: \" text-align:=\"\" times=\"\">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong style=\"margin: 0px; padding: 0px;\">Đ&igrave;nh Minh</strong></p>
',title='Đài phát thanh Từ Sơn | Thời sự tổng hợp',keyword='Đài phát thanh Từ Sơn | Thời sự tổng hợp',description='Đài phát thanh Từ Sơn | Thời sự tổng hợp' where Id=1;
