insert into quang_cao (name,img,top,bottom,link,vi_tri) values ('','/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/Hinh_w_DH.jpg','1','0','','1');
update quang_cao set name='',img='/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/Hinh_w_DH.jpg',top='1',bottom='0',link='',vi_tri='1' where id=1;
insert into quang_cao (name,img,top,bottom,link,vi_tri) values ('Học tập','/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/Anh_hoc_tap_2.jpg','0','1','','2');
insert into quang_cao (name,img,top,bottom,link,vi_tri) values ('','/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/bien-dao-la-que-huong.jpg','0','0','','3');
insert into quang_cao (name,img,top,bottom,link,vi_tri) values ('','/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/danhchoquangcao-daituson.gif','0','0','','4');
update quang_cao set active='1',name='',img='/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/Hinh_w_DH.jpg',top='1',bottom='0',link='',vi_tri='1' where id=1;
update quang_cao set active='1',name='Học tập',img='/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/Anh_hoc_tap_2.jpg',top='0',bottom='1',link='',vi_tri='2' where id=2;
update quang_cao set active='1',name='',img='/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/bien-dao-la-que-huong.jpg',top='0',bottom='0',link='',vi_tri='3' where id=3;
update quang_cao set active='1',name='',img='/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/danhchoquangcao-daituson.gif',top='0',bottom='0',link='',vi_tri='4' where id=4;
insert into quang_cao (active,name,img,top,bottom,link,vi_tri) values ('0','','/daituson/view/admin/Themes/kcfinder/upload/images/quang_cao/ngay-vi-nguoi-ngheo.jpg','0','0','','5');
